<a href="https://colab.research.google.com/github/andy-matsu/andy_matsu/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [6]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [9]:
arr = np.array(lista)

In [10]:

type(arr)

numpy.ndarray

In [12]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matriz[0, 1]

2

In [18]:
arr[1:4]

array([2, 3, 4])

In [19]:
arr[::2]

array([1, 3, 5])

In [29]:
matriz[1: , 0:2]

array([[4, 5],
       [7, 8]])

# Sección nueva

# Sección nueva